services:
  backend:
    image: ghcr.io/outfit-lab-tpi/backend-tpi:${IMAGE_TAG:-latest}
    container_name: backend_app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/outfit-lab-tpi/frontend-tpi:${IMAGE_TAG:-latest}
    container_name: frontend_app
    restart: unless-stopped

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/conf.d/default.conf
      # Volúmenes compartidos con Certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # El comando se ejecutará manualmente la primera vez
    # y luego se puede configurar para renovar automáticamente.
    command: renew

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 5 * * *" --cleanup

volumes:
  certbot_conf:
    driver: local
  certbot_www:
    driver: local
